2019/09/04 13:23:23 [emerg] 4680#1512: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
2019/09/04 13:23:44 [emerg] 1544#4772: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
2019/09/04 13:23:47 [emerg] 5588#3236: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
2019/09/04 13:24:11 [emerg] 7768#6896: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
2019/09/04 17:29:28 [error] 3644#12588: *34 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /program/python HTTP/1.1", upstream: "http://127.0.0.1:8001/program/python", host: "localhost", referrer: "http://localhost/program/list"
2019/09/04 17:29:32 [error] 3644#12588: *34 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /program/list HTTP/1.1", upstream: "http://127.0.0.1:8001/program/list", host: "localhost", referrer: "http://localhost/"
2019/09/04 19:28:20 [error] 3644#12588: *63 client intended to send too large body: 1570435 bytes, client: 127.0.0.1, server: localhost, request: "POST /program/python/1/subject/create HTTP/1.1", host: "localhost", referrer: "http://localhost/program/python/1/subject/create"
